<?php
	$user = Zend_Auth::getInstance()->getIdentity();
	if (!isset($user) || $user->is_vip != 1):
?>
	<a href="<?php echo $this->BaseUrl();?>/payment/order/sales/source/direct/campaign/big-banner" target="_blank"  id="banner-box">
		<div id="banner-box-content">
			<img src="<?php echo $this->BaseUrl();?>/img/global/banner/banner-1.png">
			<div id="banner-btn">Đặt ngay</div> 
		</div>
		<div class="clear-both"></div>
	</a>
	<div class="clear-both"></div>
<?php endif;?>

<style>
	#banner-btn {
		display: block;
		height: 50px;
		width: 250px;
		text-transform: uppercase;
		text-align: center;
		vertical-align: middle;
		padding-top: 12px;
		box-sizing: border-box;
		color: #fff;
		text-decoration: none;
		font-size: 18px;
		font-weight: bold;
		/* border-radius: 6px; */
		margin: 0px 20px;
		 border: 2px solid #fff; 
		display: block;
		/*margin: 30px auto;*/
		/*background: #b00000;*/
		position: absolute;
		right: -4px;
		bottom: 86px;
	}

	#banner-box-content {
		position: relative;
	}

	#banner-box img {
		border: 1px solid #E8E8E8;
		width: 960px;
		box-sizing: border-box;
	}

	#banner-box {
		margin-bottom: 17px;
		overflow: hidden; 
		display: block;
	}

	@-webkit-keyframes glowing {   
		0% { background-color: #004A7F; -webkit-box-shadow: 0 0 3px #004A7F; }   
		50% { background-color: #0094FF; -webkit-box-shadow: 0 0 10px #0094FF; }   
		100% { background-color: #004A7F; -webkit-box-shadow: 0 0 3px #004A7F; } 
		}   
	@-moz-keyframes glowing {   
		0% { background-color: #004A7F; -moz-box-shadow: 0 0 3px #004A7F; }   
		50% { background-color: #0094FF; -moz-box-shadow: 0 0 10px #0094FF; }   
		100% { background-color: #004A7F; -moz-box-shadow: 0 0 3px #004A7F; } 
	}   
	@-o-keyframes glowing {   
		0% { background-color: #004A7F; box-shadow: 0 0 3px #004A7F; }   
		50% { background-color: #0094FF; box-shadow: 0 0 10px #0094FF; }   
		100% { background-color: #004A7F; box-shadow: 0 0 3px #004A7F; } 
	}  
	@keyframes glowing {   
		0% { background-color: #004A7F; box-shadow: 0 0 3px #004A7F; }   
		50% { background-color: #0094FF; box-shadow: 0 0 10px #0094FF; }   
		100% { background-color: #004A7F; box-shadow: 0 0 3px #004A7F; } 
	}   
	#banner-btn {   
		-webkit-animation: glowing 1500ms infinite;   
		-moz-animation: glowing 1500ms infinite;   
		-o-animation: glowing 1500ms infinite;   
		animation: glowing 1500ms infinite; 
	}

	.clear-both {
		clear: both;
	}


</style>